### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by guiaramos** [cahilfoley/react-snowfall#15]
Hi there, thanks for your lib.

We are facing the following error on build:

![Screen Shot 2020-11-11 at 6 03 58 PM](https://user-images.githubusercontent.com/49703106/98791354-4a6f8580-2448-11eb-9196-8ee8c5d2a32f.png)

we are using nextjs:
 "next": "^9.4.0"

**Comment by giverz** [comment]
Window object isn't available when rendering on the server. You have to load the module only on the client side, either in useEffect or like below (note the prop disabling ssr): 

`import dynamic from "next/dynamic";
const Snowfall = dynamic(() => import("react-snowfall"), { ssr: false });`
