### ISSUE TITLE
Accepting `SnowflakeProps` in `Snowfall` component

### ISSUE THREAD

**Issue by phosphene47** [cahilfoley/react-snowfall#18]
It would be nice if snowflakes can be customized by passing `SnowflakeProps` to the `Snowfall` component. I find it a bit strange that individual `Snowflake`s are already customizable, but it becomes impossible when using the Snowfall component because the [default config is constant](https://github.com/cahilfoley/react-snowfall/blob/master/src/Snowfall.tsx#L19).

An example use case would be [reversing the direction of the snow](https://github.com/cahilfoley/react-snowfall/blob/master/src/Snowflake.ts#L17) by setting `wind: [0.5, 2]`.

**Comment by cahilfoley** [comment]
@phosphene47 Sorry I missed this, that's a great idea - I wrote the snowflakes with that in mind but never actually exposed it. I'll implement this when I get some time soon!

**Comment by cahilfoley** [comment]
This has been resolved in the version 1.1.0 release.

The demo has been updated to include most of the new properties.
