### ISSUE TITLE
Doesnt work with nextjs (window is undefined)

### ISSUE THREAD

**Issue by bhatvikrant** [cahilfoley/react-snowfall#22]
<img width="1440" alt="Screenshot 2021-11-09 at 2 23 18 PM" src="https://user-images.githubusercontent.com/50735025/140892938-3ed6b80c-b969-47d7-843f-e8b4bc6d756d.png">

**Comment by bhatvikrant** [comment]
this PR should fix it IMO

https://github.com/cahilfoley/react-snowfall/pull/23

**Comment by bhatvikrant** [comment]
Just found out this closed issue here https://github.com/cahilfoley/react-snowfall/issues/15

**Comment by cahilfoley** [comment]
Thanks for raising this, it turns out that the config item that was causing the build to fail wasn't being used anymore so it's been removed in [v1.1.1](https://github.com/cahilfoley/react-snowfall/releases/tag/v1.1.1).
