### ISSUE TITLE
Error when scrolling down on phone

### ISSUE THREAD

**Issue by pozitp** [cahilfoley/react-snowfall#36]
![image](https://user-images.githubusercontent.com/61188367/151496552-eff550a5-9916-48b7-a371-12cdd29d8f24.jpeg)

The snow-covered zone seems to be cut off by the first rendered position. 

Next.JS 12.0.9
React Snowfall 1.1.2

**Comment by spearkkk** [comment]
@pozitp , 
```
<Snowfall
  style={{
    position: 'fixed',
    width: '100vw',
    height: '100vh'
  }}
/>
```

Could you add style like this?
It works to me

**Comment by cahilfoley** [comment]
Thanks @spearkkk, this is referenced in the [positioning section of the README](https://github.com/cahilfoley/react-snowfall#positioning)
