### ISSUE TITLE
Can't control the origin of snow flakes

### ISSUE THREAD

**Issue by informsharique** [cahilfoley/react-snowfall#45]
There's no option to control from where the snow flakes originate. There should be an option for that. For eg. I want it to originate from top right but unfortunately it only originates from top left

**Comment by cahilfoley** [comment]
The snowflakes are randomly spread out along the top of the component , the default `wind` settings will blow them to the right which might make it appear like they are originating from the left. If you pass the `wind` prop as something like the below this will make them blow in the other direction and achieve the look you are after.

```tsx
<Snowfall wind={[-2, 0.5]} />
```
