### ISSUE TITLE
Getting warning in when running in nextjs

### ISSUE THREAD

**Issue by informsharique** [cahilfoley/react-snowfall#46]
Hi, I'm getting this warning when using inside nextjs.
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes

**Comment by cahilfoley** [comment]
Hi, that warning message is valid - this component doesn't do anything when it's rendered on the server so it should only be rendered on the client.
