### ISSUE TITLE
Using custom images return the following error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by luansantosti** [cahilfoley/react-snowfall#60]
Hey Cahil, first of all, thank you for this solution, it works great!!!

I'm trying to use some custom images but I'm getting this error:

![Screen Shot 2022-12-15 at 16 35 09](https://user-images.githubusercontent.com/6179731/207950936-2d25adf1-c089-434f-8962-f2514d79596d.png)

My code: 
```
const snowflake1 = document.createElement('img')
snowflake1.src = '../../assets/images/bird.svg'

const images = [snowflake1]
```
  
```
  <Snowfall
          style={{ zIndex: 5, filter: 'blur(2px)' }}
          snowflakeCount={183}
          radius={[0.5, 8.5]}
          wind={[-1, 1]}
          speed={[0, 2]}
          color={'#fff'}
          images={images}
        />
```

do you have any idea on what I'm doing wrong?

**Comment by devoren** [comment]
I also use svg element and it works fine without any error, maybe the svg file has some problem?

**Comment by luansantosti** [comment]
I tried jpg, png also, so I believe that's another problem :/

**Comment by devoren** [comment]
Can you post the code where you are using the lib?

**Comment by luansantosti** [comment]
I've posted the code above.. but here is a codesandbox with the library, I just tried to use the logo.png that is already there as a image to replace the snow.. https://codesandbox.io/s/loving-ardinghelli-4gskwl?file=/src/App.tsx

**Comment by devoren** [comment]
Have you tried this on a local IDE? Codesandbox throws an error:
**Unable to open 'Snowflake.js': File not found (file:///sandbox/node_modules/react-snowfall/lib/Snowflake.js).**

**Comment by TemurbekRuziyev** [comment]
@luansantosti  I think svgs don't work, because I also use svg and it doesn't work.
Then I changed it with .png format, Now it's working prefectly
