### ISSUE TITLE
Vanilla JS

### ISSUE THREAD

**Issue by xHyroM** [cahilfoley/react-snowfall#63]
Can you do support for JS without react? That would be really cool :D

**Comment by cahilfoley** [comment]
I imagine that would be possible 👍 if I find some time I'll try to make something that works without react.

**Comment by cahilfoley** [comment]
Hey @xHyroM, sorry this took a while, the new version 2.0.0 release has split the snowfall rendering out into a pure vanilla JS implementation that is then internally used in the React component, but you can access it yourself. You can use now use the `SnowfallCanvas` class to use this effect in plain JS (or any other framework for that matter). Here's an example of how to use it with plain JS [StackBlitz](https://stackblitz.com/edit/vitejs-vite-mdbtb2?file=src%2Fmain.ts).

Hope this is what you were after!
