### ISSUE TITLE
Error: Can't resolve './SnowfallCanvas'

### ISSUE THREAD

**Issue by daniel6miller** [cahilfoley/react-snowfall#73]
I am running npm 10.2.4, react 18.2.0 and react-snowfall 2.1.0. 

Error is: 
ERROR in ./node_modules/react-snowfall/lib/Snowfall.js 2:0-50
Module not found: Error: Can't resolve './SnowfallCanvas' in 'C:....client\node_modules\react-snowfall\lib'
Did you mean 'SnowfallCanvas.js'?
BREAKING CHANGE: The request './SnowfallCanvas' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

Same for 
Module not found: Error: Can't resolve './Snowflake' in 'C:......client\node_modules\react-snowfall\lib'
Did you mean 'Snowflake.js'?
Module not found: Error: Can't resolve './hooks' in 'C:.........client\node_modules\react-snowfall\lib'
Did you mean 'hooks.js'?

Let me know how to fix this. Or if it gets fixed
Thanks.

**Comment by lbrtaxel** [comment]
Hello !
You can fix it by downgrade the version of react-snowfall to `1.2.1`

**Comment by lbrtaxel** [comment]
> I am running npm 10.2.4, react 18.2.0 and react-snowfall 2.1.0.
> 
> Error is: ERROR in ./node_modules/react-snowfall/lib/Snowfall.js 2:0-50 Module not found: Error: Can't resolve './SnowfallCanvas' in 'C:....client\node_modules\react-snowfall\lib' Did you mean 'SnowfallCanvas.js'? BREAKING CHANGE: The request './SnowfallCanvas' failed to resolve only because it was resolved as fully specified (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '_.mjs' file, or a '_.js' file where the package.json contains '"type": "module"'). The extension in the request is mandatory for it to be fully specified. Add the extension to the request.
> 
> Same for Module not found: Error: Can't resolve './Snowflake' in 'C:......client\node_modules\react-snowfall\lib' Did you mean 'Snowflake.js'? Module not found: Error: Can't resolve './hooks' in 'C:.........client\node_modules\react-snowfall\lib' Did you mean 'hooks.js'?
> 
> Let me know how to fix this. Or if it gets fixed Thanks.

Hello @daniel6miller !
You can fix it by downgrade the version of react-snowfall to 1.2.1

**Comment by cahilfoley** [comment]
This issue should hopefully be resolved in the [latest release v2.1.1](https://github.com/cahilfoley/react-snowfall/releases/tag/v2.1.1)
