### ISSUE TITLE
Horizontal movement instead of vertical in first couple of seconds

### ISSUE THREAD

**Issue by LightScrool** [cahilfoley/react-snowfall#78]
I noticed this issue when tried to set wind=[0, 0]
At first snowflakes moves sideways instead of vertically

To fix it, you need to replace `...wind` and `...speed` here:
https://github.com/cahilfoley/react-snowfall/blob/eacc15ef44cf59cfe00ff0f3ef4b4a1f737c7d3f/packages/react-snowfall/src/Snowflake.ts#L131
https://github.com/cahilfoley/react-snowfall/blob/eacc15ef44cf59cfe00ff0f3ef4b4a1f737c7d3f/packages/react-snowfall/src/Snowflake.ts#L132

At least, this fix worked for me (i applied it by pnpm patch)

**Comment by cahilfoley** [comment]
Thanks for raising this! I'll take a look at this shortly and see if I can get something similar patched in.

**Comment by cahilfoley** [comment]
This was fixed in [v2.1.2](https://github.com/cahilfoley/react-snowfall/releases/tag/v2.1.2), thanks again!
